services:
  mysql:
    image: mysql
    env_file:
      - .env.production
    ports:
      - '3307:3307'
  users_crud:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    volumes:
      - ./src:/usr/src/app/src